# Generated by Django 3.2.18 on 2023-05-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230423_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70, verbose_name='Ваше имя')),
                ('user_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Userpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.user')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Парольи',
            },
        ),
    ]
