# Generated by Django 3.2.18 on 2023-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_user_userpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpassword',
        ),
    ]
