# Generated by Django 3.2.18 on 2023-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_delete_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=50, verbose_name='Ваш пароль'),
        ),
    ]
