# Generated by Django 3.2.18 on 2023-05-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
