# Generated by Django 3.2.18 on 2023-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
