# Generated by Django 3.2.18 on 2023-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20230512_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='default_user_name', max_length=40, unique=True),
        ),
    ]
