# Generated by Django 3.2.18 on 2023-05-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
