# Generated by Django 3.2.18 on 2023-05-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
