# Generated by Django 3.2.18 on 2023-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=50, null=True, verbose_name='password2'),
        ),
    ]
