# Generated by Django 3.2.18 on 2023-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20230520_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
